"use client";

import React, { useState, useEffect, useRef } from "react";
import { useRouter, usePathname } from "next/navigation";
import { signOut } from "firebase/auth";
import { auth } from "@/lib/firebase";
import { useAuth } from "@/lib/useAuth";
import { WardMap } from "@/components/WardMap";
import { LoadingSpinner } from "@/components/LoadingSpinner";

const DEPARTMENTS = [
  { dept: "Water Supply Dept", resolution: 92, days: 1.8, sla: "EXCEPTIONAL", active: 14, color: "#16A34A", bg: "#DCFCE7" },
  { dept: "Roads & Infrastructure", resolution: 68, days: 4.2, sla: "AT RISK", active: 42, color: "#DC2626", bg: "#FEF2F2" },
  { dept: "Solid Waste Mgmt", resolution: 88, days: 2.1, sla: "STANDARD", active: 28, color: "#64748B", bg: "#F1F5F9" },
  { dept: "Electricity & Lighting", resolution: 95, days: 1.2, sla: "EXCEPTIONAL", active: 9, color: "#16A34A", bg: "#DCFCE7" },
  { dept: "Urban Planning", resolution: 45, days: 7.5, sla: "DELAYED", active: 18, color: "#DC2626", bg: "#FEF2F2" },
];

const COMPLAINT_CATEGORIES = [
  { label: "Water Supply Issues", count: 82, max: 82 },
  { label: "Potholes & Road Repair", count: 64, max: 82 },
  { label: "Waste Management", count: 45, max: 82 },
  { label: "Street Lighting", count: 31, max: 82 },
  { label: "Illegal Encroachments", count: 25, max: 82 },
];

const NAV_ITEMS = [
  { label: "Dashboard", href: "/mla" },
  { label: "Complaints", href: "/cases" },
  { label: "Reports", href: "/reports" },
];

export default function MLADashboardPage() {
  const router = useRouter();
  const pathname = usePathname();
  const { user, loading } = useAuth();
  const [activeTab, setActiveTab] = useState<"Resolution Rate" | "Complaint Volume">("Resolution Rate");
  const [searchQuery, setSearchQuery] = useState("");
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [profileDropdownOpen, setProfileDropdownOpen] = useState(false);
  const dropdownRef = useRef<HTMLDivElement>(null);

  // Close dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(e.target as Node)) {
        setProfileDropdownOpen(false);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  // Auth guard
  useEffect(() => {
    if (!loading && !user) {
      router.replace("/login");
    }
  }, [user, loading, router]);

  const handleSignOut = async () => {
    await fetch("/api/v1/auth/session", { method: "DELETE" });
    await signOut(auth);
    router.replace("/login");
  };

  const handleDownload = () => {
    const data = `Pune Ward Cluster — Weekly Report
Generated: ${new Date().toLocaleDateString("en-IN")}
==============================================
Total Complaints : 247
Avg Resolution   : 2.3 days
Satisfaction     : 78%
Top Issue        : Water Supply (82 cases)

DEPARTMENT PERFORMANCE
----------------------
Water Supply Dept          : 92% — EXCEPTIONAL  (1.8 days avg)
Roads & Infrastructure     : 68% — AT RISK       (4.2 days avg)
Solid Waste Management     : 88% — STANDARD      (2.1 days avg)
Electricity & Lighting     : 95% — EXCEPTIONAL   (1.2 days avg)
Urban Planning             : 45% — DELAYED        (7.5 days avg)

Generated by P-CRM — Smart Public Governance System
Pune Municipal Corporation`;
    const blob = new Blob([data], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `ward-report-${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return <div style={{ minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center" }}><LoadingSpinner color="#2563EB" size={32} /></div>;
  }

  return (
    <div style={{
      minHeight: "100vh",
      backgroundColor: "#F8FAFC",
      fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    }}>
      {/* ── Responsive CSS ── */}
      <style>{`
        .mla-nav-desktop { display: flex; }
        .mla-hamburger { display: none; }
        .mla-search-desktop { display: block; }
        .mla-mobile-menu { display: none; }
        @media (max-width: 768px) {
          .mla-nav-desktop { display: none !important; }
          .mla-hamburger { display: flex !important; }
          .mla-search-desktop { display: none !important; }
          .mla-mobile-menu { display: flex !important; }
        }
      `}</style>

      {/* ── TOP NAVBAR ── */}
      <header style={{
        backgroundColor: "#1B2A4A",
        padding: "0 24px",
        flexShrink: 0,
        position: "sticky",
        top: 0,
        zIndex: 100,
      }}>
        <div style={{
          height: 64,
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          gap: 16,
          maxWidth: 1400,
          margin: "0 auto",
        }}>
          {/* Left — branding + nav */}
          <div style={{ display: "flex", alignItems: "center", gap: 28 }}>
            <div style={{ cursor: "pointer" }} onClick={() => router.push("/mla")}>
              <div style={{ fontSize: 15, fontWeight: 700, color: "#FFFFFF" }}>Pune Ward Cluster</div>
              <div style={{ fontSize: 10, color: "#94A3B8", marginTop: 1 }}>MLA Constituency Portal</div>
            </div>

            {/* Desktop nav */}
            <nav className="mla-nav-desktop" style={{ gap: 4, alignItems: "center" }}>
              {NAV_ITEMS.map((item) => {
                const isActive = pathname === item.href;
                return (
                  <div
                    key={item.label}
                    onClick={() => router.push(item.href)}
                    style={{
                      padding: "6px 14px",
                      borderRadius: 6,
                      fontSize: 13,
                      fontWeight: isActive ? 600 : 400,
                      color: isActive ? "#FFFFFF" : "#94A3B8",
                      backgroundColor: isActive ? "rgba(255,255,255,0.12)" : "transparent",
                      cursor: "pointer",
                      transition: "all 0.2s ease",
                    }}
                    onMouseEnter={(e) => { if (!isActive) e.currentTarget.style.color = "#FFFFFF"; e.currentTarget.style.backgroundColor = "rgba(255,255,255,0.08)"; }}
                    onMouseLeave={(e) => { if (!isActive) { e.currentTarget.style.color = "#94A3B8"; e.currentTarget.style.backgroundColor = "transparent"; } }}
                  >
                    {item.label}
                  </div>
                );
              })}
            </nav>

            {/* Hamburger button (mobile) */}
            <button
              className="mla-hamburger"
              onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
              style={{
                background: "none", border: "none", cursor: "pointer",
                color: "#FFFFFF", fontSize: 22, padding: 4,
                display: "none", alignItems: "center", justifyContent: "center",
              }}
              aria-label="Toggle menu"
            >
              {mobileMenuOpen ? "✕" : "☰"}
            </button>
          </div>

          {/* Right — search + notification + profile */}
          <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
            <input
              className="mla-search-desktop"
              type="text"
              placeholder="Search wards, complaints…"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              style={{
                height: 36,
                padding: "0 14px",
                borderRadius: 8,
                border: "1px solid rgba(255,255,255,0.15)",
                background: "rgba(255,255,255,0.08)",
                color: "#FFFFFF",
                fontSize: 13,
                outline: "none",
                width: 200,
              }}
            />
            <div style={{
              width: 36, height: 36, borderRadius: "50%",
              background: "rgba(255,255,255,0.15)",
              display: "flex", alignItems: "center", justifyContent: "center",
              cursor: "pointer", fontSize: 16, position: "relative",
            }}>
              🔔
              <span style={{
                position: "absolute", top: 4, right: 4,
                width: 8, height: 8, borderRadius: "50%",
                background: "#EF4444", border: "1.5px solid #1B2A4A",
              }} />
            </div>

            {/* Profile avatar + dropdown */}
            <div ref={dropdownRef} style={{ position: "relative" }}>
              <div
                onClick={() => setProfileDropdownOpen(!profileDropdownOpen)}
                style={{
                  width: 36, height: 36, borderRadius: "50%",
                  background: "#2563EB",
                  display: "flex", alignItems: "center", justifyContent: "center",
                  color: "#FFF", fontWeight: 700, fontSize: 14, cursor: "pointer",
                  border: profileDropdownOpen ? "2px solid #60A5FA" : "2px solid transparent",
                  transition: "border 0.2s ease",
                }}
              >
                MLA
              </div>

              {/* Dropdown menu */}
              {profileDropdownOpen && (
                <div style={{
                  position: "absolute",
                  top: "calc(100% + 8px)",
                  right: 0,
                  width: 220,
                  background: "#FFFFFF",
                  borderRadius: 10,
                  border: "1px solid #E2E8F0",
                  boxShadow: "0 8px 24px rgba(0,0,0,0.12)",
                  overflow: "hidden",
                  zIndex: 200,
                  animation: "fadeIn 0.15s ease",
                }}>
                  <div style={{ padding: "14px 16px", borderBottom: "1px solid #F1F5F9" }}>
                    <div style={{ fontSize: 13, fontWeight: 600, color: "#1B2A4A" }}>
                      {user?.email?.split("@")[0] || "MLA User"}
                    </div>
                    <div style={{ fontSize: 11, color: "#94A3B8", marginTop: 2 }}>
                      {user?.email || "mla@pune.gov.in"}
                    </div>
                    <div style={{
                      display: "inline-block", marginTop: 6,
                      fontSize: 10, fontWeight: 700, color: "#2563EB",
                      background: "#EFF6FF", padding: "2px 8px", borderRadius: 10,
                    }}>
                      MLA
                    </div>
                  </div>
                  <div style={{ padding: "6px" }}>
                    <button
                      onClick={() => { setProfileDropdownOpen(false); router.push("/settings"); }}
                      style={{
                        width: "100%", padding: "8px 12px", border: "none",
                        background: "none", cursor: "pointer", textAlign: "left",
                        fontSize: 13, color: "#1B2A4A", borderRadius: 6,
                        display: "flex", alignItems: "center", gap: 8,
                      }}
                      onMouseEnter={(e) => e.currentTarget.style.background = "#F8FAFC"}
                      onMouseLeave={(e) => e.currentTarget.style.background = "none"}
                    >
                      ⚙️ Settings
                    </button>
                    <button
                      onClick={handleSignOut}
                      style={{
                        width: "100%", padding: "8px 12px", border: "none",
                        background: "none", cursor: "pointer", textAlign: "left",
                        fontSize: 13, color: "#DC2626", borderRadius: 6,
                        display: "flex", alignItems: "center", gap: 8,
                      }}
                      onMouseEnter={(e) => e.currentTarget.style.background = "#FEF2F2"}
                      onMouseLeave={(e) => e.currentTarget.style.background = "none"}
                    >
                      🚪 Sign Out
                    </button>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>

        {/* ── Mobile nav menu ── */}
        {mobileMenuOpen && (
          <div
            className="mla-mobile-menu"
            style={{
              display: "none",
              flexDirection: "column",
              gap: 2,
              paddingBottom: 12,
              borderTop: "1px solid rgba(255,255,255,0.1)",
            }}
          >
            {NAV_ITEMS.map((item) => {
              const isActive = pathname === item.href;
              return (
                <div
                  key={item.label}
                  onClick={() => { router.push(item.href); setMobileMenuOpen(false); }}
                  style={{
                    padding: "10px 14px",
                    borderRadius: 6,
                    fontSize: 14,
                    fontWeight: isActive ? 600 : 400,
                    color: isActive ? "#FFFFFF" : "#94A3B8",
                    backgroundColor: isActive ? "rgba(255,255,255,0.12)" : "transparent",
                    cursor: "pointer",
                  }}
                >
                  {item.label}
                </div>
              );
            })}
            <div
              onClick={handleSignOut}
              style={{
                padding: "10px 14px",
                borderRadius: 6,
                fontSize: 14,
                fontWeight: 500,
                color: "#F87171",
                cursor: "pointer",
                marginTop: 4,
                borderTop: "1px solid rgba(255,255,255,0.1)",
                paddingTop: 14,
              }}
            >
              🚪 Sign Out
            </div>
          </div>
        )}
      </header>

      {/* ── MAIN CONTENT ── */}
      <main style={{ padding: "32px 32px 48px", maxWidth: 1280, margin: "0 auto" }}>

        {/* HERO SECTION */}
        <div style={{ marginBottom: 28 }}>
          <h1 style={{ margin: "0 0 4px", fontSize: 26, fontWeight: 800, color: "#1B2A4A" }}>
            Constituency Overview — Pune Ward Cluster
          </h1>
          <p style={{ margin: 0, fontSize: 14, color: "#64748B" }}>
            Welcome back, Public Representative. Here's a real-time view of your constituency.
          </p>
        </div>

        {/* KPI CARDS */}
        <div style={{ display: "flex", gap: 20, marginBottom: 32, flexWrap: "wrap" }}>
          {[
            {
              label: "Total Complaints",
              value: "247",
              delta: "+12% vs last month",
              deltaColor: "#D97706",
              icon: "📋",
              iconBg: "#FEF3C7",
            },
            {
              label: "Avg Resolution",
              value: "2.3 days",
              delta: "↓ 0.5 days improvement",
              deltaColor: "#16A34A",
              icon: "⚡",
              iconBg: "#DCFCE7",
            },
            {
              label: "Citizen Satisfaction",
              value: "78%",
              delta: "↑ +5% this month",
              deltaColor: "#16A34A",
              icon: "⭐",
              iconBg: "#EFF6FF",
            },
          ].map((card) => (
            <div
              key={card.label}
              style={{
                flex: "1 1 200px",
                background: "#FFFFFF",
                borderRadius: 12,
                border: "1px solid #E2E8F0",
                padding: "20px 24px",
                boxShadow: "0 1px 3px rgba(0,0,0,0.05)",
              }}
            >
              <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 12 }}>
                <div style={{
                  width: 36, height: 36, borderRadius: 8,
                  background: card.iconBg, display: "flex",
                  alignItems: "center", justifyContent: "center", fontSize: 18,
                }}>
                  {card.icon}
                </div>
                <div style={{ fontSize: 13, color: "#64748B", fontWeight: 500 }}>{card.label}</div>
              </div>
              <div style={{ fontSize: 30, fontWeight: 800, color: "#1B2A4A", marginBottom: 6 }}>
                {card.value}
              </div>
              <div style={{ fontSize: 12, color: card.deltaColor, fontWeight: 500 }}>{card.delta}</div>
            </div>
          ))}
        </div>

        {/* TWO-COLUMN SECTION */}
        <div style={{ display: "flex", gap: 24, marginBottom: 32, flexWrap: "wrap" }}>
          {/* LEFT — Ward Map (60%) */}
          <div style={{ flex: "3 1 500px", background: "#FFFFFF", borderRadius: 12, border: "1px solid #E2E8F0", padding: 24, boxShadow: "0 1px 3px rgba(0,0,0,0.05)" }}>
            {/* Map header + toggle */}
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>
              <div>
                <div style={{ fontSize: 16, fontWeight: 700, color: "#1B2A4A" }}>Ward Map</div>
                <div style={{ fontSize: 12, color: "#94A3B8", marginTop: 2 }}>Pune Municipal Corporation boundaries</div>
              </div>
              <div style={{ display: "flex", background: "#F8FAFC", borderRadius: 8, padding: 4, gap: 2 }}>
                {(["Resolution Rate", "Complaint Volume"] as const).map((tab) => (
                  <button
                    key={tab}
                    onClick={() => setActiveTab(tab)}
                    style={{
                      padding: "5px 12px",
                      borderRadius: 6,
                      fontSize: 12,
                      fontWeight: 600,
                      border: "none",
                      cursor: "pointer",
                      background: activeTab === tab ? "#FFFFFF" : "transparent",
                      color: activeTab === tab ? "#1B2A4A" : "#94A3B8",
                      boxShadow: activeTab === tab ? "0 1px 3px rgba(0,0,0,0.1)" : "none",
                    }}
                  >
                    {tab}
                  </button>
                ))}
              </div>
            </div>

            {/* OpenStreetMap Embed */}
            <WardMap height={340} />

            {/* Legend */}
            <div style={{ display: "flex", gap: 20, marginTop: 14, flexWrap: "wrap" }}>
              {[
                { color: "#16A34A", label: "Resolution >80%" },
                { color: "#D97706", label: "Resolution 60–80%" },
                { color: "#DC2626", label: "Resolution <60%" },
              ].map((leg) => (
                <div key={leg.label} style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 12, color: "#64748B" }}>
                  <span style={{ width: 10, height: 10, borderRadius: "50%", background: leg.color, display: "inline-block" }} />
                  {leg.label}
                </div>
              ))}
            </div>
          </div>

          {/* RIGHT — Top Complaints (40%) */}
          <div style={{ flex: "2 1 300px", background: "#FFFFFF", borderRadius: 12, border: "1px solid #E2E8F0", padding: 24, boxShadow: "0 1px 3px rgba(0,0,0,0.05)", display: "flex", flexDirection: "column" }}>
            <div style={{ fontSize: 16, fontWeight: 700, color: "#1B2A4A", marginBottom: 4 }}>
              Top Complaints by Category
            </div>
            <div style={{ fontSize: 12, color: "#94A3B8", marginBottom: 20 }}>This week's distribution</div>

            <div style={{ display: "flex", flexDirection: "column", gap: 16, flex: 1 }}>
              {COMPLAINT_CATEGORIES.map((cat) => (
                <div key={cat.label}>
                  <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 6 }}>
                    <span style={{ fontSize: 13, color: "#1B2A4A", fontWeight: 500 }}>{cat.label}</span>
                    <span style={{ fontSize: 13, fontWeight: 700, color: "#2563EB" }}>{cat.count}</span>
                  </div>
                  <div style={{ height: 8, background: "#EFF6FF", borderRadius: 4, overflow: "hidden" }}>
                    <div style={{
                      width: `${(cat.count / cat.max) * 100}%`,
                      height: "100%",
                      background: "linear-gradient(90deg, #2563EB, #60A5FA)",
                      borderRadius: 4,
                      transition: "width 0.8s ease",
                    }} />
                  </div>
                </div>
              ))}
            </div>

            <button
              onClick={handleDownload}
              style={{
                marginTop: 24,
                width: "100%",
                height: 44,
                background: "#1B2A4A",
                color: "#FFFFFF",
                border: "none",
                borderRadius: 8,
                fontSize: 14,
                fontWeight: 600,
                cursor: "pointer",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                gap: 8,
              }}
            >
              ⬇ Download Weekly Report
            </button>
          </div>
        </div>

        {/* DEPARTMENT PERFORMANCE TABLE */}
        <div style={{ background: "#FFFFFF", borderRadius: 12, border: "1px solid #E2E8F0", overflow: "hidden", boxShadow: "0 1px 3px rgba(0,0,0,0.05)" }}>
          <div style={{ padding: "20px 24px", borderBottom: "1px solid #E2E8F0", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
            <div>
              <div style={{ fontSize: 16, fontWeight: 700, color: "#1B2A4A" }}>Department Performance</div>
              <div style={{ fontSize: 12, color: "#94A3B8", marginTop: 2 }}>SLA compliance by department</div>
            </div>
            <div style={{ fontSize: 12, color: "#16A34A", fontWeight: 600, background: "#DCFCE7", padding: "4px 10px", borderRadius: 20 }}>
              Live Data
            </div>
          </div>
          <div style={{ overflowX: "auto" }}>
            <table style={{ width: "100%", borderCollapse: "collapse", textAlign: "left" }}>
              <thead>
                <tr style={{ background: "#F8FAFC", borderBottom: "1px solid #E2E8F0" }}>
                  {["Department", "Resolution %", "Avg Days", "SLA Status", "Active Cases"].map((h) => (
                    <th key={h} style={{ padding: "12px 20px", fontSize: 12, color: "#64748B", fontWeight: 600 }}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {DEPARTMENTS.map((row, idx) => (
                  <tr
                    key={idx}
                    style={{ borderBottom: idx < DEPARTMENTS.length - 1 ? "1px solid #F1F5F9" : "none" }}
                  >
                    <td style={{ padding: "16px 20px", fontSize: 14, fontWeight: 600, color: "#1B2A4A" }}>{row.dept}</td>
                    <td style={{ padding: "16px 20px" }}>
                      <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                        <div style={{ width: 80, height: 6, background: "#F1F5F9", borderRadius: 3, overflow: "hidden" }}>
                          <div style={{ width: `${row.resolution}%`, height: "100%", background: row.color, borderRadius: 3 }} />
                        </div>
                        <span style={{ fontSize: 13, fontWeight: 700, color: row.color }}>{row.resolution}%</span>
                      </div>
                    </td>
                    <td style={{ padding: "16px 20px", fontSize: 14, color: "#64748B" }}>{row.days} days</td>
                    <td style={{ padding: "16px 20px" }}>
                      <span style={{
                        background: row.bg,
                        color: row.color,
                        fontSize: 11,
                        fontWeight: 700,
                        padding: "4px 10px",
                        borderRadius: 20,
                        letterSpacing: "0.3px",
                      }}>
                        {row.sla}
                      </span>
                    </td>
                    <td style={{ padding: "16px 20px", fontSize: 14, color: "#1B2A4A", fontWeight: 600 }}>{row.active}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </main>
    </div>
  );
}
